name: Deploy github pages
#on:
#    push:
#      branches:
#        - master
on: [workflow_dispatch, push]

jobs:
  gh-pages-deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup assest branch variable
        run: "echo ::set-env name=ASSET_BRANCH::deploy-asset"

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  12.x

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install npm dependency
        run: npm ci

      - name: Run npm build script (prod, using jsdelivr)
        run: npm run build:prod
        env:
          PUBLIC_PATH: "https://cdn.jsdelivr.net/gh/${{ github.repository }}@$ASSET_BRANCH/"

      # TODO: Copying asset, push to asset branch & github-pages branch
