name: Deploy github pages
#on:
#    push:
#      branches:
#        - master
on: [workflow_dispatch, push]

jobs:
  build-production-files:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup assest branch variable
        run: echo ::set-env name=ASSET_BRANCH::deploy-asset

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  12.x

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install npm dependency
        run: npm ci

      - name: Run npm build script (prod, using jsdelivr)
        run: npm run build:prod
        env:
          PUBLIC_PATH: "https://cdn.jsdelivr.net/gh/${{ github.repository }}@$ASSET_BRANCH/"
      
      - name: Move assets to root folder
        run: mv ./dist/assets ./assets
      
      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: ./assets
      
      - name: Upload deploy file
        uses: actions/upload-artifact@v2
        with:
          name: deployment-file
          path: ./dist
          
  commit-assets:
    name: Commit Assets
    runs-on: ubuntu-latest
    needs: [build-production-files]
    steps:
      - name: Setup assest branch variable
        run: echo ::set-env name=ASSET_BRANCH::deploy-asset
      
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: deploy-asset
      
      - name: Config git
        run: git config user.name "Assest Bot"
      
      - name: Download Assests
        uses: actions/download-artifact@v2
        with:
          name: assets
          path: .
        
      - name: Display directory structure (for debuging)
        run: ls -R
          
      - name: Add assests to git
        run: git add --all
      
      - name: Commit Assests
        run: |
          git commit -m "Compiled deployment assest for $(git rev-parse --short $GITHUB_SHA) (uwu)"
          
      - name: Push to Github
        run: git push origin HEAD:${ASSET_BRANCH} --force
          
