name: Deploy github pages
#on:
#    push:
#      branches:
#        - master
on: [workflow_dispatch, push]

jobs:
  build-production-files:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup assest branch variable
        run: echo ::set-env name=ASSET_BRANCH::deploy-asset

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  12.x

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install npm dependency
        run: npm ci

      - name: Run npm build script (prod, using jsdelivr)
        run: npm run build:prod
        env:
          PUBLIC_PATH: "https://cdn.jsdelivr.net/gh/${{ github.repository }}@$ASSET_BRANCH/"
      
      - name: Move assets to root folder
        run: mv ./dist/assets ./assets
      
      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: ./assets
      
      - name: Upload deploy file
        uses: actions/upload-artifact@v2
        with:
          name: deployment-file
          path: ./dist
          
  commit-assets:
    name: Commit Assets
    runs-on: ubuntu-latest
    needs: [build-production-files]
    steps:
      - name: Setup assest branch variable
        run: echo ::set-env name=ASSET_BRANCH::deploy-asset
      
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: deploy-asset
      
      - name: Config git
        run: git config user.name "0w0 Deploy Bot"
      
      - name: Download Assests
        uses: actions/download-artifact@v2
        with:
          name: assets
          path: ./assets
        
      - name: List directory (for debugging)
        run: ls -R
        
      - name: git status before tracking (for debugging)
        run: git status --short ./assests
        
      - name:  Add assests to git
        run: git add ./assets
        
      - name: git status after tracking (for debugging)
        run: git status --short ./assests
          
      - name: Commit and push assests if necessary
        run: |
          if [[ $(git status --short ./assests) != '' ]]; then
            git commit -m "Compiled deployment assest for $(git rev-parse --short $GITHUB_SHA) (0w0)"
            git push origin HEAD:${ASSET_BRANCH} --force
          else
            echo "No need to commit as there's no changes"
          fi

  deploy-github-page:
    name: Deploy to github pages branch
    runs-on: ubuntu-latest
    needs: [build-production-files, commit-assets]
    steps:
      
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Config git
        run: git config user.name "0w0 Deploy Bot"
      
      - name: Create orphan github pages branch
        run: git checkout --orphan gh-pages
        
      - name: Download deployment files
        uses: actions/download-artifact@v2
        with:
          name: deployment-file
          path: ./dep
        
      - name: Add files to git
        run: git --work-tree dep add --all
        
      - name: Commit and push deployment if necessary
        run: |
          if [[ $(git status --short) != '' ]]; then
            git commit -m "Compiled deployment for $(git rev-parse --short $GITHUB_SHA) (0w0)"
            git push origin HEAD:gh-pages --force
          else
            echo "No need to commit as there's no changes"
          fi
